version: '3'
services:
        postgres-master:
            build:
                context: .
                dockerfile: Dockerfile-PostgreSQL
            ports:
                - "5432"
            volumes:
                - data_volume:/bitnami/postgresql
            environment:
                - POSTGRESQL_DATABASE=pidsvc
                - POSTGRESQL_PASSWORD=apassword
                - POSTGRESQL_REPLICATION_MODE=master
                - POSTGRESQL_REPLICATION_USER=pidsvc-admin
                - POSTGRESQL_REPLICATION_PASSWORD=apassword
                - POSTGRESQL_POSTGRES_PASSWORD=postgres
        pidsvc-master:
            build:
                context: .
                dockerfile: Dockerfile-pidsvcMaster
            depends_on:
                - postgres-master
            expose:
                - "8080"
                - "8009"
        apache-master:
            build:
                context: .
                dockerfile: Dockerfile-ApacheMaster
            depends_on:
                - pidsvc-master
            ports:
                - "8095:80"
        postgres-replica:
            image: "bitnami/postgresql:latest"
            ports:
                - "5432"
            depends_on:
                - postgres-master
            environment:
                - POSTGRESQL_REPLICATION_MODE=slave
                - POSTGRESQL_REPLICATION_USER=pidsvc-admin
                - POSTGRESQL_REPLICATION_PASSWORD=apassword
                - POSTGRESQL_MASTER_HOST=postgres-master
                - POSTGRESQL_PASSWORD=apassword
                - POSTGRESQL_MASTER_PORT_NUMBER=5432
        pidsvc-replica:
            build:
                context: .
                dockerfile: Dockerfile-pidsvcReplica
            depends_on:
                - postgres-replica
            expose:
                - "8080"
                - "8009"
        apache-replica:
            build:
                context: .
                dockerfile: Dockerfile-ApacheReplica
            depends_on:
                - pidsvc-replica
            ports:
                - "8099:80"       
volumes:
    data_volume:
