version: '3'

services:
  pygeoapi:
    image: internetofwater/pygeoapi-geoconnex:latest
    user: root
    ports:
      - "5000:80"
    volumes:
      - ./ext_data:/ext_data
      - ./pygeoapi.config.yml:/pygeoapi/local.config.yml
