# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: info.geoconnex.us #change to your hostname if running your own instance
        port: 80
    url: https://info.geoconnex.us #change to host URL  if running your own instance
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: true
    limit: 50
    map:
        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: ERROR
    logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: geoconnex reference features
        description: Provides reference features for geoconnex.us.
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/internetofwater/geoconnex.us
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Team geoconnex
        url: https://github.com/internetofwater/geoconnex.us
    contact:
        address: 2111 Campus Dr
        city: Durham
        stateorprovince: North Carolina
        postalcode: 27708
        country: USA
        email: kyle.onda@duke.edu
        url: https://internetofwater.org
        role: pointOfContact

resources:
    hu02:
        type: collection
        title: HU02
        description: Two-digit Hydrologic Regions
        keywords:
            - Hydrologic Regions
        context:
            - NAME: https://schema.org/name
            - gnis_url: https://schema.org/subjectOf
            - uri: "@id"
        links:
            - type: application/html
              rel: canonical
              title: data source
              href: https://www.usgs.gov/core-science-systems/ngp/national-hydrography/access-national-hydrography-products
              hreflang: en-US
        extents:
            spatial:
                bbox: [-170,15,-51,72]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: null
        provider:
            name: GeoJSON
            data: /ext_data/hu02.geojson
            id_field: HUC2
    nat_aq:
        type: collection
        title: National Aquifers
        description: National Aquifers of the United States
        uri_stem: https://geoconnex.us/ref/nat_aq/
        keywords:
            - National Aquifers
            - Principle Aquifers
        context:
            - AQ_NAME: https://schema.org/name
            - LINK: https://schema.org/subjectOf
            - uri: "@id"
        links:
            - type: application/html
              rel: canonical
              title: data source
              href: https://cida.usgs.gov/ngwmn/
              hreflang: en-US
            - type: application/html
              rel: canonical
              title: data source
              href: https://cida.usgs.gov/ngwmn/
              hreflang: en-US
        extents:
            spatial:
                bbox: [-170,15,-51,72]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: null
        provider:
            name: GeoJSON
            data: /ext_data/nat_aq.geojson
            id_field: NAT_AQFR_CD
