name: CI/CD for yourls server

on:
  push:
    branches:
      - 'dev'
    #   - 'master'
    # paths:
    #   - 'PID-server/**'

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Upload backup to GCP Bucket
        id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: PID-server/backup
          destination: yourls-data/backup
          headers: |-
            content-type: application/x-gzip

      - name: Push to mysql
        run: |-
          gcloud sql import sql yourls-mysql gs://yourls-data/backup/yourls.sql.gz \
            --database=yourls \
            --quiet
